port : "8080"

db : 
      username : "crm_user" #"crm_user_actual"
      host : "localhost" #"postgres"
      port : "5432"
      dbname : "crm_db" #"crm_db"
      sslmode : "disable"
redis:
      host: "localhost" #"redis" "localhost"
      port: "6379"
      db: 0 