port : "8080"

db : 
      username : "crm_user" #"crm_user_actual"
      host : "localhost" #"postgres"
      port : "5432"
      dbname : "crm_db" #"crm_db"
      sslmode : "disable"
redis:
      host: "localhost" #"redis" "localhost"
      port: "6379"
      db: 0 
kafka:
      bootstrap_servers:
        - "localhost:9092"
      topic_orders: "order_events"
      group_id: "analytics-service"
clickhouse:
      host: "localhost"
      port: "9000"
      database: "default"
      user: "analytics"
      password: "secret"